import Link from "next/link";
import { asc } from "drizzle-orm";
import { getUserDb, owned } from "@/db/user-db";
import { academicEvents, disciplines, topics, exams } from "@/db/schema";
import { AgendaForm } from "@/components/agenda-form";
import { finishAcademicEvent } from "@/app/copilot-actions";
import { agendaKinds, daysUntil, localDay } from "@/lib/copilot";
export default async function AgendaPage({searchParams}:{searchParams:Promise<{editar?:string;erro?:string;salvo?:string}>}) {
  const {db,userId}=await getUserDb(); const query=await searchParams;
  const [events,courses,concepts,old]=await Promise.all([db.select().from(academicEvents).where(owned(academicEvents,userId)).orderBy(asc(academicEvents.date)),db.select().from(disciplines).where(owned(disciplines,userId)),db.select().from(topics).where(owned(topics,userId)),db.select().from(exams).where(owned(exams,userId)).orderBy(asc(exams.examDate))]);
  const edit=events.find(e=>e.id===query.editar); const today=localDay();
  return <div className="space-y-5"><header><Link href="/dashboard" className="focus-back">← Hoje</Link><h1 className="page-title">Agenda acadêmica</h1><p className="muted mt-2">Prepare o que você precisa aprender antes de cada prazo.</p></header>{query.erro && <p role="alert" className="callout">Confira o nome, o tipo e a data do compromisso.</p>}{query.salvo && <p role="status" className="callout">Compromisso salvo. Seu plano foi atualizado.</p>}<div className="grid gap-5 lg:grid-cols-[1fr_360px]"><section className="space-y-3">{!events.length && !old.length && <p className="empty">Seu primeiro compromisso começa aqui.</p>}{events.map(e => <article className="card p-5 space-y-3" key={e.id}><span className="badge">{agendaKinds[e.kind as keyof typeof agendaKinds]} · {e.completed ? "Concluído" : daysUntil(e.date,today)<0 ? "Prazo passado" : `${daysUntil(e.date,today)} dia(s)`}</span><h2 className="section-title break-words">{e.name}</h2><p className="muted">{courses.find(c=>c.id===e.disciplineId)?.name} · {e.date.split("-").reverse().join("/")}</p>{e.notes && <p className="whitespace-pre-wrap break-words">{e.notes}</p>}<div className="flex flex-wrap gap-2"><Link className="btn btn-secondary" href={`/agenda?editar=${e.id}#formulario`}>Editar</Link><form action={finishAcademicEvent}><input type="hidden" name="id" value={e.id}/><input type="hidden" name="completed" value={e.completed?"0":"1"}/><button className="btn btn-ghost">{e.completed?"Reabrir":"Marcar concluído"}</button></form></div></article>)}{old.map(e=><Link className="card block p-5" key={e.id} href={`/provas/${e.id}`}><span className="badge">Prova já cadastrada</span><h2 className="section-title mt-3">{e.name}</h2><p className="muted">{e.examDate.split("-").reverse().join("/")}</p></Link>)}</section><aside id="formulario" className="card p-5 h-fit"><h2 className="section-title mb-4">{edit?"Editar compromisso":"Novo compromisso"}</h2>{courses.length?<AgendaForm key={edit?.id || "new"} courses={courses} topics={concepts} event={edit}/>:<Link className="btn btn-primary" href="/disciplinas">Cadastrar disciplina</Link>}</aside></div></div>;
}
