import { Brain, CheckCircle2, FlaskConical, MessageCircleQuestion } from "lucide-react";
import { asc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { difficulties, disciplines, quizAttempts, quizQuestions, quizzes, studySessions, topics, tutorMessages } from "@/db/schema";
import { createDifficulty, generateQuiz, scheduleReview, submitQuiz, testUnderstanding } from "@/app/actions";
import { SubmitButton } from "@/components/submit-button";
import { TutorChat } from "@/components/tutor-chat";

export default async function StudyPage({searchParams}:{searchParams:Promise<{topico?:string;dificuldade?:string;quiz?:string;tentativa?:string;entendimento?:string;erro?:string}>}){
  const query=await searchParams;const db=getDb();const[disciplineRows,topicRows]=await Promise.all([db.select().from(disciplines).where(eq(disciplines.status,"ATIVA")),db.select().from(topics).orderBy(topics.name)]);
  let activeDifficulty:typeof difficulties.$inferSelect|undefined;let messages:typeof tutorMessages.$inferSelect[]=[];
  if(query.dificuldade){[activeDifficulty]=await db.select().from(difficulties).where(eq(difficulties.id,query.dificuldade)).limit(1);if(activeDifficulty)messages=await db.select().from(tutorMessages).where(eq(tutorMessages.difficultyId,activeDifficulty.id)).orderBy(asc(tutorMessages.createdAt));}
  let activeQuiz:typeof quizzes.$inferSelect|undefined;let questions:typeof quizQuestions.$inferSelect[]=[];let attempt:typeof quizAttempts.$inferSelect|undefined;
  if(query.quiz){[activeQuiz]=await db.select().from(quizzes).where(eq(quizzes.id,query.quiz)).limit(1);questions=await db.select().from(quizQuestions).where(eq(quizQuestions.quizId,query.quiz));if(query.tentativa)[attempt]=await db.select().from(quizAttempts).where(eq(quizAttempts.id,query.tentativa)).limit(1);}
  let understanding:typeof studySessions.$inferSelect|undefined;if(query.entendimento)[understanding]=await db.select().from(studySessions).where(eq(studySessions.id,query.entendimento)).limit(1);
  const selectedTopicId=query.topico||activeDifficulty?.topicId||activeQuiz?.topicId||"";const selectedTopic=topicRows.find(t=>t.id===selectedTopicId);const selectedDisciplineId=selectedTopic?.disciplineId||activeDifficulty?.disciplineId||activeQuiz?.disciplineId||disciplineRows[0]?.id||"";
  return <div className="space-y-7"><header><p className="muted text-sm">Tutor pessoal</p><h1 className="page-title">Estudar agora</h1><p className="muted mt-2 max-w-2xl">Conte o que travou, peça um diagnóstico ou teste se você realmente entendeu.</p></header>
    {query.erro&&<p className="rounded-xl border p-4 text-sm" style={{borderColor:"var(--danger)",color:"var(--danger)"}}>Não foi possível concluir a chamada de IA. Confira OPENAI_API_KEY e OPENAI_MODEL no EasyPanel e tente novamente.</p>}
    {activeDifficulty&&<section className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_310px]"><TutorChat difficultyId={activeDifficulty.id} messages={messages.map(({id,role,mode,content})=>({id,role,mode,content}))}/><aside className="space-y-4"><div className="card p-5"><span className="label">Relato inicial</span><p className="text-sm leading-6">{activeDifficulty.originalReport}</p><div className="mt-4 flex flex-wrap gap-2"><span className="badge">{activeDifficulty.level.replaceAll("_"," ")}</span><span className="badge">{activeDifficulty.occurrences} ocorrências</span></div></div><div className="card p-5"><h3 className="mb-3 font-extrabold">Programar revisão</h3><form action={scheduleReview} className="space-y-3"><input type="hidden" name="topicId" value={activeDifficulty.topicId}/><div className="grid grid-cols-2 gap-2">{[[1,"Amanhã"],[3,"3 dias"],[7,"7 dias"],[15,"15 dias"]].map(([days,label])=><button key={days} name="days" value={days} className="btn btn-secondary text-xs">{label}</button>)}</div></form></div></aside></section>}
    {activeQuiz&&<section className="card p-5 md:p-7"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 className="section-title flex items-center gap-2"><FlaskConical size={20}/>{activeQuiz.title}</h2><p className="muted mt-1 text-sm">{questions.length} questões · corrigidas sem nova chamada de IA</p></div>{attempt&&<strong className="display text-3xl" style={{color:attempt.score>=70?"var(--brand)":"var(--danger)"}}>{attempt.score}%</strong>}</div>{attempt?<div className="space-y-4">{questions.map((question,index)=>{const answer=attempt.answers[question.id];const ok=answer===question.correctAnswer;return <div key={question.id} className="rounded-xl border p-4" style={{borderColor:ok?"var(--brand)":"var(--danger)"}}><div className="flex gap-3"><strong>{index+1}.</strong><div><strong>{question.prompt}</strong><p className="mt-2 text-sm">Sua resposta: {answer||"Sem resposta"}</p>{!ok&&<p className="mt-1 text-sm">Correta: {question.correctAnswer}</p>}<p className="muted mt-2 text-sm">{question.explanation}</p></div></div></div>})}<div className="flex flex-wrap gap-3"><a className="btn btn-primary" href="/estudar">Novo estudo</a>{activeQuiz.topicId&&<form action={scheduleReview}><input type="hidden" name="topicId" value={activeQuiz.topicId}/><button name="days" value="3" className="btn btn-secondary">Revisar em 3 dias</button></form>}</div></div>:<form action={submitQuiz} className="space-y-6"><input type="hidden" name="quizId" value={activeQuiz.id}/>{questions.map((question,index)=><fieldset key={question.id} className="rounded-xl border p-4" style={{borderColor:"var(--line)"}}><legend className="px-2 font-bold">{index+1}. {question.prompt}</legend><div className="mt-3 grid gap-2">{question.options.map(option=><label key={option} className="flex cursor-pointer gap-3 rounded-xl bg-[var(--surface-2)] p-3 text-sm"><input type="radio" name={`q_${question.id}`} value={option} required/><span>{option}</span></label>)}</div></fieldset>)}<button className="btn btn-primary">Finalizar e corrigir</button></form>}</section>}
    {understanding&&<section className="card p-6"><h2 className="section-title mb-4 flex items-center gap-2"><CheckCircle2 size={20}/>Avaliação de entendimento</h2><p className="whitespace-pre-wrap text-sm leading-7">{understanding.note}</p></section>}
    {!activeDifficulty&&!activeQuiz&&<div className="grid gap-6 lg:grid-cols-2"><section className="card p-5 md:p-6"><h2 className="section-title mb-2 flex items-center gap-2"><MessageCircleQuestion size={20}/>Estou com dificuldade</h2><p className="muted mb-6 text-sm">Escreva do seu jeito. O tutor começa descobrindo exatamente onde você travou.</p><form action={createDifficulty} className="space-y-4"><label><span className="label">Disciplina</span><select className="field" name="disciplineId" required defaultValue={selectedDisciplineId}><option value="">Selecione</option>{disciplineRows.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label><span className="label">Tópico</span><select className="field" name="topicId" required defaultValue={selectedTopicId}><option value="">Selecione</option>{topicRows.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div><span className="label">Como você está?</span><div className="grid gap-2 sm:grid-cols-3">{[["NAO_ENTENDI","😵 Não entendi"],["PARCIAL","🤔 Parcialmente"],["QUERO_TESTAR","🧪 Quero testar"]].map(([v,l])=><label key={v} className="rounded-xl bg-[var(--surface-2)] p-3 text-center text-xs font-bold"><input className="mr-1" type="radio" name="level" value={v} defaultChecked={v==="NAO_ENTENDI"}/>{l}</label>)}</div></div><label><span className="label">Conte o que aconteceu</span><textarea className="field min-h-32" name="report" required maxLength={2500} placeholder="Estou confundindo TCP e UDP e não sei quando cada um é usado..."/></label><input type="hidden" name="mode" value="DIAGNOSTICAR"/><SubmitButton pendingText="Analisando sua dificuldade..." className="btn btn-primary w-full"><Brain size={18}/>Começar diagnóstico</SubmitButton></form></section>
      <div className="space-y-6"><section className="card p-5 md:p-6"><h2 className="section-title mb-2 flex items-center gap-2"><FlaskConical size={20}/>Gerar quiz</h2><p className="muted mb-5 text-sm">As questões e respostas ficam salvas. A correção não gasta IA.</p><form action={generateQuiz} className="space-y-4"><label><span className="label">Disciplina</span><select className="field" name="disciplineId" required defaultValue={selectedDisciplineId}><option value="">Selecione</option>{disciplineRows.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label><span className="label">Tópico</span><select className="field" name="topicId" required defaultValue={selectedTopicId}><option value="">Selecione</option>{topicRows.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label><span className="label">Quantidade</span><select className="field" name="count"><option value="5">5 questões</option><option value="10">10 questões</option></select></label><SubmitButton pendingText="Criando questões..." className="btn btn-secondary w-full">Criar quiz</SubmitButton></form></section>
      <section className="card p-5 md:p-6"><h2 className="section-title mb-2">Quero testar se entendi</h2><p className="muted mb-5 text-sm">Explique sem consultar o material e receba uma avaliação curta.</p><form action={testUnderstanding} className="space-y-4"><label><span className="label">Disciplina</span><select className="field" name="disciplineId" required defaultValue={selectedDisciplineId}><option value="">Selecione</option>{disciplineRows.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label><span className="label">Tópico</span><select className="field" name="topicId" required defaultValue={selectedTopicId}><option value="">Selecione</option>{topicRows.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label><span className="label">Desafio</span><input className="field" name="question" required placeholder="Explique a diferença entre hashing e criptografia"/></label><label><span className="label">Sua explicação</span><textarea className="field min-h-28" name="answer" required/></label><SubmitButton pendingText="Avaliando..." className="btn btn-secondary w-full">Avaliar entendimento</SubmitButton></form></section></div></div>}
  </div>
}
