"use client";
import { useEffect, useState, useTransition } from "react";
import { answerMock, finishMock } from "@/app/mock-actions";
import { SubmitButton } from "@/components/submit-button";
export function MockRunner({id,questions,answers:initial,expiresAt}:{id:string;questions:{id:string;prompt:string;options:string[]}[];answers:Record<string,string>;expiresAt:string}) {
  const [answers,setAnswers]=useState(initial),[index,setIndex]=useState(0),[seconds,setSeconds]=useState<number|null>(null),[error,setError]=useState(""); const [pending,startTransition]=useTransition();
  useEffect(()=>{const tick=()=>setSeconds(Math.max(0,Math.floor((Date.parse(expiresAt)-Date.now())/1000)));tick(); const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[expiresAt]);
  const q=questions[index]; const expired=seconds===0;
  return <section className="card p-5 sm:p-8 space-y-5"><div className="flex justify-between gap-3"><span className="badge">{index+1}/{questions.length}</span><span aria-live="off">{seconds===null?"Carregando tempo…":`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`}</span></div><p className="muted text-sm">Respostas salvas a cada escolha. O gabarito aparece ao finalizar.</p>{expired&&<p role="alert" className="callout">Tempo encerrado. Finalize para conferir seu resultado.</p>}<h2 className="text-xl font-bold break-words">{q.prompt}</h2><div className="space-y-3">{q.options.map(option=><button className={`quiz-choice w-full ${answers[q.id]===option?"quiz-choice-selected":""}`} type="button" key={option} disabled={pending||expired} aria-pressed={answers[q.id]===option} onClick={()=>{setError("");startTransition(async()=>{try{if(!await answerMock(id,q.id,option)){setError("O tempo acabou ou o simulado já foi finalizado. Confira seu resultado.");return;}setAnswers(a=>({...a,[q.id]:option}));}catch{setError("Não foi possível salvar. Tente novamente.");}});}}>{option}</button>)}</div>{error&&<p role="alert">{error}</p>}<div className="flex flex-wrap justify-between gap-3"><button className="btn btn-secondary" type="button" disabled={index===0||pending} onClick={()=>setIndex(i=>i-1)}>Anterior</button>{index<questions.length-1&&<button className="btn btn-primary" type="button" disabled={pending} onClick={()=>setIndex(i=>i+1)}>Próxima</button>}</div><form action={finishMock}><input type="hidden" name="id" value={id}/><p className="muted text-sm mb-3">{Object.keys(answers).length}/{questions.length} respondidas. Questões em branco contam como erro.</p><SubmitButton pendingText="Calculando…" disabled={pending} className="btn btn-primary w-full">Finalizar simulado</SubmitButton></form></section>;
}
