import Link from "next/link";
import { LogOut, ShieldCheck } from "lucide-react";
import { ThemeToggle } from "./theme-toggle";
import { MobileNavigation } from "./mobile-navigation";
import { DesktopNavigation } from "./desktop-navigation";

export function Shell({ children, isTest = false }: { children: React.ReactNode; isTest?: boolean }) {
  return <div className="app-shell min-h-screen md:grid md:grid-cols-[208px_minmax(0,1fr)]"><aside className="desktop-only app-sidebar sticky top-0 h-screen border-r p-4"><Link href="/disciplinas" className="mb-9 flex items-center gap-3 px-2"><span className="brand-mark"><ShieldCheck size={23}/></span><div className="min-w-0"><strong className="display text-lg">Cyber<span className="text-[var(--brand)]">Study</span></strong><div className="muted text-[10px]">Aprender de verdade</div></div></Link><DesktopNavigation/><div className="absolute bottom-4 left-4 right-4 space-y-2"><ThemeToggle/><form action="/api/auth/logout" method="post"><button className="btn btn-ghost w-full"><LogOut size={17}/>Sair</button></form></div></aside><div className="min-w-0"><MobileNavigation/><header className="app-topbar sticky top-0 z-20 flex h-16 items-center justify-between border-b px-4 md:px-8"><Link href="/disciplinas" className="flex items-center gap-2 md:hidden"><span className="brand-mark h-9 w-9"><ShieldCheck size={20}/></span><strong className="display">Cyber<span className="text-[var(--brand)]">Study</span></strong></Link><div className="hidden md:block"><strong className="text-sm">Seu espaço de evolução</strong><p className="muted text-xs">Um passo por vez.</p></div><ThemeToggle/></header><main className="app-main mx-auto max-w-[1180px] px-4 py-5 pb-28 md:px-8 md:py-8 md:pb-10">{isTest && <div role="status" className="mb-4 rounded-xl border border-amber-400 bg-[var(--surface-2)] px-3 py-2 text-xs font-bold">CONTA DE TESTE · progresso separado</div>}{children}</main></div></div>;
}
