import Link from "next/link";
import { BarChart3, BookOpen, Brain, CalendarCheck, ClipboardList, History, Home, LogOut, ShieldCheck, UserRound } from "lucide-react";
import { ThemeToggle } from "./theme-toggle";
import { MobileNavigation } from "./mobile-navigation";

const mainNav = [["Hoje", "/dashboard", Home], ["Estudar", "/disciplinas", BookOpen], ["Tutor", "/estudar", Brain], ["Progresso", "/progresso", BarChart3], ["Perfil", "/perfil", UserRound]] as const;
const secondaryNav = [["Revisões", "/revisoes", CalendarCheck], ["Provas", "/provas", ClipboardList], ["Histórico", "/historico", History]] as const;

export function Shell({ children }: { children: React.ReactNode }) {
  return <div className="app-shell min-h-screen md:grid md:grid-cols-[244px_minmax(0,1fr)]"><aside className="desktop-only app-sidebar sticky top-0 h-screen border-r p-5"><Link href="/dashboard" className="mb-8 flex items-center gap-3 px-2"><span className="brand-mark"><ShieldCheck size={24}/></span><div><strong className="display text-xl">Cyber<span className="text-[var(--brand)]">Study</span></strong><div className="muted text-[11px]">Aprender de verdade</div></div></Link><p className="label px-3">Aprender</p><nav className="space-y-1">{mainNav.map(([label, href, Icon]) => <Link key={href} href={href} className="side-link"><Icon size={19}/>{label}</Link>)}</nav><p className="label mt-7 px-3">Organizar</p><nav className="space-y-1">{secondaryNav.map(([label, href, Icon]) => <Link key={href} href={href} className="side-link"><Icon size={18}/>{label}</Link>)}</nav><div className="absolute bottom-5 left-5 right-5 space-y-2"><ThemeToggle/><form action="/api/auth/logout" method="post"><button className="btn btn-ghost w-full"><LogOut size={17}/>Sair</button></form></div></aside><div className="min-w-0"><MobileNavigation/><header className="app-topbar sticky top-0 z-20 flex h-16 items-center justify-between border-b px-4 md:px-8"><Link href="/dashboard" className="flex items-center gap-2 md:hidden"><span className="brand-mark h-9 w-9"><ShieldCheck size={20}/></span><strong className="display">Cyber<span className="text-[var(--brand)]">Study</span></strong></Link><div className="hidden md:block"><strong className="text-sm">Seu espaço de evolução</strong><p className="muted text-xs">Um passo por vez.</p></div><ThemeToggle/></header><main className="app-main mx-auto max-w-[1440px] px-4 py-5 pb-28 md:px-8 md:py-8 md:pb-10">{children}</main></div></div>;
}
