import Link from "next/link";
import { copilotData } from "@/lib/copilot-data";
import { daysUntil, materialState, preparationPlan } from "@/lib/copilot";
export default async function SemesterPage(){
  const data=await copilotData();
  return <div className="space-y-6"><header><Link className="focus-back" href="/progresso">← Progresso</Link><h1 className="page-title">Seu semestre</h1><p className="muted mt-2">Preparação pelos resultados, com o próximo prazo à vista.</p></header><div className="grid gap-4 md:grid-cols-2">{data.trails.map(({course,trail})=>{
    const concepts=data.concepts.filter(c=>c.disciplineId===course.id), mastery=concepts.length?Math.round(concepts.reduce((sum,c)=>sum+c.mastery,0)/concepts.length):null;
    const event=data.events.filter(e=>e.disciplineId===course.id&&e.date>=data.today).sort((a,b)=>a.date.localeCompare(b.date))[0];
    const weak=concepts.filter(c=>c.mastery<70).sort((a,b)=>a.mastery-b.mastery);
    const days=event?daysUntil(event.date,data.today):null;
    const unmeasured=trail.topicRows.filter(t=>!concepts.some(c=>c.topicId===t.id)).length;
    const risk=days!==null&&days<=7&&(mastery===null||mastery<70||unmeasured>0)?"Prioridade alta":weak.length?"Pontos para reforçar":"Manter revisões";
    const preparation=event?preparationPlan(event,trail.topicRows.map(t=>({id:t.id,mastery:concepts.find(c=>c.topicId===t.id)?.mastery||0,assessed:concepts.some(c=>c.topicId===t.id)})),data.today):null;
    return <article className="card p-5 space-y-4" key={course.id}><span className="badge">{risk}</span><h2 className="section-title">{course.name}</h2><p className="text-3xl font-bold">{mastery===null?"Sem diagnóstico":`${mastery}%`}<span className="muted block text-sm font-normal mt-1">domínio observado nos conceitos avaliados</span></p><p className="muted text-sm">{unmeasured} assunto(s) ainda sem evidência · {trail.completed}/{trail.total} aulas concluídas</p><p>{event?`${event.name} · em ${days} dia(s)`:"Nenhuma avaliação futura cadastrada"}</p><>{preparation&&<div className="callout"><strong>{preparation.phase}</strong><p className="mt-2">{preparation.remaining} conceito(s) para preparar · meta de {preparation.perDay} por dia até o prazo.</p><p className="muted text-sm mt-2">O plano de Hoje seleciona o próximo passo dentro do seu tempo disponível.</p></div>}</><p className="muted">Material: {trail.currentUnit?.title||trail.groups.at(-1)?.title||"Envie seu primeiro PDF"}</p><p className="badge">{materialState(trail.total,trail.completed,concepts)}</p>{weak.length>0&&<div><h3 className="font-bold">O que precisa de atenção</h3>{weak.slice(0,3).map(c=><p className="muted mt-2" key={c.id}>{c.name} · {c.mastery}%{c.errors>1?` · ${c.errors} erros registrados`:""}</p>)}</div>}<details><summary className="font-bold cursor-pointer min-h-11">Mapa de conceitos</summary><div className="mt-3 space-y-3">{concepts.map(c=><div key={c.id} className="rounded-xl bg-[var(--surface-2)] p-3"><strong>{c.name}</strong><p className="muted text-sm">{c.mastery>=80?"Forte":c.mastery>=50?"Em desenvolvimento":"Precisa reforçar"} · {c.mastery}% · {c.samples} respostas avaliadas</p>{c.lastError&&<p className="mt-2 text-sm">Última lacuna: {c.lastError}</p>}</div>)}{trail.topicRows.filter(t=>!concepts.some(c=>c.topicId===t.id)).map(t=><p key={t.id} className="muted">{t.name} · Ainda não avaliado</p>)}</div></details><Link className="btn btn-primary w-full" href={trail.href}>Continuar estudo</Link><Link className="btn btn-ghost w-full" href={`/simulado?disciplina=${course.id}`}>Testar preparação</Link></article>;
  })}</div><Link className="btn btn-secondary" href="/agenda">Organizar agenda</Link></div>;
}
